version: "3"
services:
  core_api:
    build: .
    container_name: "core-api-container"
    ports:
      - "8887:15400"
    volumes:
      # - ./app/:/app
      - db-data:/app/data/

volumes:
  db-data:
